### ISSUE TITLE
Site Not Deployed to GitHub Pages! Can't grade it!

### ISSUE THREAD

**Issue by sandblasta** [PhoenixOwl24/Week-10-Project-1---One-Page-Design-Restaurant-Web-Page#1]
Kaila -- I cant grade this because it's not deployed to GitHub Pages!

**Comment by PhoenixOwl24** [comment]
Oh okay. Can you show me how to do that again? I had a classmate help me
with the portfolio website project.

**Comment by sandblasta** [comment]
on your repository, go to settings > pages. 
in the middle of the page, change the dropdown from "None" to "Main", then hit "Save". 
wait a couple minutes, then refresh the page. You should see a url appear at the top of the page.

**Comment by PhoenixOwl24** [comment]
https://phoenixowl24.github.io/Week-10-Project-1---One-Page-Design-Restaurant-Web-Page/
I believe I fixed it?

**Comment by sandblasta** [comment]
Yes you did! 

I really enjoyed having you in my class this semester. You asked great questions, and you did great work! Enjoy your summer!
